name: whale_cnn_legacy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - numpy=1.24.*
  - pandas=1.5.*
  - scikit-learn=1.2.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - pillow=9.4.*
  - opencv=4.7.*
  - tqdm=4.65.*
  - pip:
    - tensorflow==2.13.0
    - keras==2.13.1 